### PR TITLE
fix: exclude tree shaken modules from dependencies to scan

### LINKED ISSUE #380: Suggestion: Use tree-shaking information when generating third party dependencies
At the moment, this plugin will list all imported dependencies in the license file even though I may not be using any code from those dependencies due to tree-shaking.

This could be improved substantially by not relying on the load hook to identify dependencies but instead by using the bundle information in generateBundle, which lists for each chunk the module ids included in the chunk + the rendered length (which should be 0 for tree-shaken modules).

### PR DESCRIPTION
**Pull request by mjeanroy**
Fix #380

### CODE REVIEW

File: src/index-rollup-stable.js [hunk 1]
```diff
@@ -57,6 +47,15 @@ module.exports = (options = {}) => {
      * @return {void}
      */
     renderChunk(code, chunk, outputOptions = {}) {
+      plugin.scanDependencies(
+          _.chain(chunk.modules)
+              .toPairs()
+              .reject((mod) => mod[1].isAsset)
+              .filter((mod) => mod[1].renderedLength > 0)
```
Comment (lukastaegert) [inline src/index-rollup-stable.js]: I told you that renderedLength is 0 if everything is treeshaken but would be nice to verify this is actually the case😬 Otherwise this looks good to me!

File: test/index-rollup-stable.spec.js [hunk 2]
```diff
@@ -105,7 +117,21 @@ describe('rollup-plugin-license [rollup stable]', () => {
       },
     });
 
-    instance.load('lodash');
+    const moduleId = path.join(__dirname, 'fixtures', 'fake-package', 'src', 'index.js');
+    const modules = {
+      [moduleId]: {
+        renderedExports: [],
+        removedExports: [],
+        renderedLength: 10,
```
Comment (lukastaegert) [inline test/index-rollup-stable.spec.js]: Is there a test for `renderedLength===0`?

Comment (mjeanroy) [reply test/index-rollup-stable.spec.js]: I missed to add it, thanks!

File: src/index-rollup-stable.js (hunk 1 above)
Comment (lukastaegert) [reply src/index-rollup-stable.js]: I can confirm `renderedLength === 0` works as long as the file does not have a leading comment, which is always retained. But I guess this is something we can fix on Rollup's side, so I do not see any issues here as well.

**Comment by lukastaegert** [comment]
rollup/rollup#2940 will make sure that `renderedLength === 0` actually does coincide with a module being completely tree-shaken.

File: src/index-rollup-stable.js (hunk 1 above)
Comment (mjeanroy) [reply src/index-rollup-stable.js]: Thanks @lukastaegert, sorry for the delay, but I had a lot of work ;)
